version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - g37-lanches-network

  g37-lanches-api:
    build: .
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT: dev
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSLMODE: disable
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    restart: always  # Configuração para reiniciar sempre
    networks:
      - g37-lanches-network

networks:
  g37-lanches-network:
    driver: bridge
