name: Deploy API to K8S

on:
  push:
    tags:
    - '**'

env:
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push the Docker image
      run: |
        docker build --platform linux/amd64 -t nobrucarneiro/lanches-api:production .
        docker tag nobrucarneiro/lanches-api:production nobrucarneiro/lanches-api:production
        docker push nobrucarneiro/lanches-api:production

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Update kubeconfig for EKS cluster
      run: aws eks --region us-east-1 update-kubeconfig --name $EKS_CLUSTER_NAME

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Apply Kubernetes manifest
      run: |
        kubectl rollout restart deployment/lanches-api-deployment